name: Build Release APK

on:
  workflow_dispatch:
    # Only manual trigger from Action tab; no schedule, push, or PR events.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Release APK (debug signing)
        run: ./gradlew assembleRelease

      - name: Find built APK
        id: find_apk
        run: |
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ${{ steps.find_apk.outputs.apk_path }}
          if-no-files-found: error

      - name: Print APK path
        run: echo "APK generated at ${{ steps.find_apk.outputs.apk_path }}"

      - name: Reminder for manual signing
        run: |
          echo "This APK is signed with the debug key. Download it from the workflow artifacts, sign it manually with your release key, and upload to the Release section on GitHub."
